export enum PAYMENT_METHODS {
  VISA_ELECTRON = 1,
  MAESTRO = 2,
  DOLLARS = 3,
  REAIS = 4,
  PESOS_AR = 5,
}

export const CASH_METHODS = [
  PAYMENT_METHODS.DOLLARS,
  PAYMENT_METHODS.PESOS_AR,
  PAYMENT_METHODS.REAIS,
];